"""baseline

Revision ID: 001
Revises: 
Create Date: 2026-04-15 23:44:27.220506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_slug', sa.String(length=64), nullable=False),
    sa.Column('is_logging_opted_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_game_slug'), 'chat_sessions', ['game_slug'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_slug', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spoiler_tier', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_game_slug'), 'entities', ['game_slug'], unique=False)
    op.create_index('ix_entities_game_type', 'entities', ['game_slug', 'entity_type'], unique=False)
    op.create_index(op.f('ix_entities_slug'), 'entities', ['slug'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(length=256), nullable=False),
    sa.Column('game_slug', sa.String(length=64), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_game_slug'), 'eval_runs', ['game_slug'], unique=False)
    op.create_table('passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_slug', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('spoiler_tier', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passages_content_hash'), 'passages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_passages_game_slug'), 'passages', ['game_slug'], unique=False)
    op.create_index('ix_passages_game_spoiler', 'passages', ['game_slug', 'spoiler_tier'], unique=False)
    op.create_table('query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_slug', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_log_game_slug'), 'query_log', ['game_slug'], unique=False)
    op.create_table('semantic_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_slug', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_cache_game_slug'), 'semantic_cache', ['game_slug'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('shared_threads',
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    op.drop_table('shared_threads')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_semantic_cache_game_slug'), table_name='semantic_cache')
    op.drop_table('semantic_cache')
    op.drop_index(op.f('ix_query_log_game_slug'), table_name='query_log')
    op.drop_table('query_log')
    op.drop_index('ix_passages_game_spoiler', table_name='passages')
    op.drop_index(op.f('ix_passages_game_slug'), table_name='passages')
    op.drop_index(op.f('ix_passages_content_hash'), table_name='passages')
    op.drop_table('passages')
    op.drop_index(op.f('ix_eval_runs_game_slug'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_entities_slug'), table_name='entities')
    op.drop_index('ix_entities_game_type', table_name='entities')
    op.drop_index(op.f('ix_entities_game_slug'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_chat_sessions_game_slug'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
